[workspace]
changelog_update = true
git_release_enable = true
publish = true
semver_check = true

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

body = """
## [{{ version | trim_start_matches(pat="v") }}]{% if timestamp %} - {{ timestamp | date(format="%Y-%m-%d") }}{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}

{% for commit in commits %}
- {{ commit.message | upper_first }}\
{% if commit.breaking %} [**breaking**]{% endif %}
{% endfor %}
{% endfor %}

"""

footer = """
{% for release in releases %}
{% if release.version %}
[{{ release.version | trim_start_matches(pat="v") }}]: \
  https://github.com/justin13888/cameo/releases/tag/{{ release.version }}
{% else %}
[Unreleased]: https://github.com/justin13888/cameo/compare/{{ releases | first | get(key="version") }}...HEAD
{% endif %}
{% endfor %}
"""

trim = true
postprocessors = []

[[changelog.commit_parsers]]
message = "^feat"
group = "<!-- 0 -->Added"

[[changelog.commit_parsers]]
message = "^fix"
group = "<!-- 1 -->Fixed"

[[changelog.commit_parsers]]
message = "^refactor|^perf"
group = "<!-- 2 -->Changed"

[[changelog.commit_parsers]]
message = "^docs"
group = "<!-- 3 -->Documentation"

[[changelog.commit_parsers]]
message = "^chore|^ci|^test|^build"
skip = true

[[changelog.commit_parsers]]
message = ".*"
group = "<!-- 4 -->Other"
