name: Release

on:
  push:
    tags: ['v*.*.*']

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        features:
          - "tmdb,cache"
          - "anilist"
          - "tmdb"
          - "tmdb,anilist"
          - "tmdb,anilist,cache"
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.features }}

      - name: Test (${{ matrix.features }})
        run: cargo test --no-default-features --features "${{ matrix.features }}"

  release:
    name: Publish crate
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Clippy (all features)
        run: cargo clippy --all-features -- -D warnings

      - name: Docs (all features)
        run: cargo doc --no-deps --all-features

      - name: Dry run publish
        run: cargo publish --dry-run

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
